# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tonmangram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tonmangram
  pod 'RealmSwift'
  pod 'Alamofire'
  pod 'PhoneNumberKit', '~> 3.1'
  pod 'MessageKit'
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'

  target 'TonmangramTests' do
    inherit! :search_paths
    # Pods for testing
   pod 'RxBlocking', '6.2.0'
   pod 'RxTest', '6.2.0'
  end

  target 'TonmangramUITests' do
    # Pods for testing
  end

end
